version: 2
jobs:
 build:
  docker:
   - image: circle/node
  steps:
   - checkout
   - run: echo "npm installing"
   - run: npm install
   - run: CI=true npm run build
  test:
   docker:
    - image: circleci/node
    steps:
     - checkout:
     - run: echo "testing"
     - run: npm test
  hithere:
    docker:
      - image: circle/node
    steps:
      - checkout
      - run: echo "hellooou"
workflows:
  version: 2
  build_test_and_lint:
   jobs:
     - build
     - hithere
     - test:
         requires:
           - hithere

