version: 2
jobs:
 bobby:
  docker:
   - image: circle/ruby:2.4.1
  steps:
   - checkout
   - run: echo "Afirst hello"
  sally:
   docker:
    - image: circleci/ruby:2.4.1
    steps:
     - checkout:
     - run: echo "double trouble"
  workflows:
   version: 2
   bobby_sally:
    jobs:
     - bobby
     - sally